# Generated by Django 4.1.1 on 2022-09-16 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='nuser',
            name='password',
        ),
    ]
