# Generated by Django 4.1.1 on 2022-09-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_nuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
