# Generated by Django 4.1.1 on 2022-09-16 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllotedHall',
            fields=[
                ('allotid', models.IntegerField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SeminarHall',
            fields=[
                ('hallid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('wifi', models.BooleanField()),
                ('projector', models.BooleanField()),
                ('speaker', models.BooleanField()),
                ('microphone', models.BooleanField()),
                ('camera', models.BooleanField()),
                ('ac', models.BooleanField()),
                ('Location', models.CharField(max_length=50)),
                ('Rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('reqid', models.IntegerField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('reason', models.TextField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('permLetter', models.FileField(upload_to='permissionLetters/')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.seminarhall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fbid', models.IntegerField(primary_key=True, serialize=False)),
                ('facAvialed', models.IntegerField()),
                ('cleanliness', models.IntegerField()),
                ('remarkd', models.TextField()),
                ('allotment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.allotedhall')),
            ],
        ),
        migrations.AddField(
            model_name='allotedhall',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.seminarhall'),
        ),
        migrations.AddField(
            model_name='allotedhall',
            name='hallRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.request'),
        ),
    ]
