# Generated by Django 4.1.1 on 2022-09-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotedhall',
            name='allotid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fbid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='reqid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seminarhall',
            name='hallid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
