# Generated by Django 4.1.1 on 2022-09-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_allotedhall_allotid_alter_feedback_fbid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotedhall',
            name='allotid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fbid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='reqid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seminarhall',
            name='hallid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
